### ISSUE TITLE
on('readable') does not immediately fire, like PassThrough

### ISSUE THREAD

**Issue by asgerf** [isaacs/minipass#36]
Hi 👋. I ran into an issue where `MiniPass` does not behave like `PassThrough`.

When calling `.on('readable', ...)` on a stream with a non-empty internal buffer:
- PassThrough immediately emits a `readable` event
- MiniPass does not

Reproduction:
```js
const MiniPass = require('minipass');
const { PassThrough } = require('stream');

test(MiniPass);
test(PassThrough);
function test(TStream) {
    console.log(TStream.name);
    const stream = new TStream();
    stream.write('Hey');
    stream.on('readable', () => {
        let chunk;
        while ((chunk = stream.read()) != null) {
            console.log(chunk);
        }
    });
}
```
Output:
```
Minipass
PassThrough
<Buffer 48 65 79>
```

I know `read()` is not recommended (I don't like it either), but some libraries seem to rely on it.

**Comment by isaacs** [comment]
Waiting on getting access to the npm publish, but this is fixed now in main.  Thanks for the nudge, not sure when node-core added that, but it's a good addition.  The "write empty string to kick the stream" thing is annoying, I agree.
