### ISSUE TITLE
An export assignment cannot be used in a module with other exported elements.  151 export = Minipass;

### ISSUE THREAD

**Issue by jcesarmobile** [isaacs/minipass#47]
Note that I don't use minipass, but some dependency of my project is.
version 4.2.7 of minipass has been released a few hours ago and it's breaking the build of my project with the mentioned message

> An export assignment cannot be used in a module with other exported elements.  151 export = Minipass;

I see that later on a 5.0.0 release was done with breaking changes, but can a new 4.2.8 version be released without breaking changes?

**Comment by yuvron** [comment]
I got the exact same problem!
Have you managed to find a solution?

**Comment by jcesarmobile** [comment]
Nope, I tried installing previous versions as direct dependencies to my project to try to force using that version. The error goes away, but a very similar one appears coming from `@types/tar` package as it's installing 4.2.7 despite I'm forcing a different version.

If you are not using `@types/tar` you can try pinning a previous version, i.e `npm install --save-exact minimist@4.2.5`

**Comment by IT-MikeS** [comment]
You can also leverage a `npm-shrinkwrap.json` file as an option if you’re using NPM

**Comment by yuvron** [comment]
> Nope, I tried installing previous versions as direct dependencies to my project to try to force using that version. The error goes away, but a very similar one appears coming from `@types/tar` package as it's installing 4.2.7 despite I'm forcing a different version.
> 
> If you are not using `@types/tar` you can try pinning a previous version, i.e `npm install --save-exact minimist@4.2.5`

Actually, @types/tar is the source of the problem in my case.

**Comment by faizvasaya** [comment]
Hey @jcesarmobile @yuvron @IT-MikeS 
Can you please propose a solution for this as it is breaking the builds.

Following is the dependency tree of my project for minipass.

└─┬ rimraf@4.4.1
  └─┬ glob@9.3.5
    ├── minipass@4.2.7
    └─┬ path-scurry@1.6.4
      └── minipass@5.0.0

**Comment by isaacs** [comment]
Published 4.2.7 which rolled back the changes introduced to the default export types.

Note that v5 is latest now, which does not use a default export, only named exports.

**Comment by jcesarmobile** [comment]
4.2.8, 4.2.7 was the broken one

Thanks! I can confirm it fix our build.

**Comment by vbrinza** [comment]
For us its 5.0.0 who breaks our build with 
```
323 export class Pack extends MiniPass {

                              ~~~~~~~~

node_modules/@types/tar/index.d.ts:379:[36]

Cannot use namespace 'MiniPass' as a type.

export interface ReadEntry extends MiniPass, HeaderProperties {
                                       ~~~~~~~~

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging

Found 2 errors in the same file, starting at: node_modules/@types/tar/index.d.ts:323
```

**Comment by jcesarmobile** [comment]
You should create a new issue for that.
But you should verify first that the problem is not in your end.
5.0.0 is a major release, which means it includes breaking changes, so you might need to do some changes to adjust accordingly.

Note that latest release of `@types/tar` requires minipass 4.x, so you might not be able to use minipass 5.x until there is a new release of `@types/tar` (and also of tar itself, as it also uses 4.x on latest release), so it might not be a bug in minipass, but an incompatibility with latest `tar`/`@types/tar` versions. Hard to tell until those are updated.
