### ISSUE TITLE
2.6.x is a breaking change on 2.5.x

### ISSUE THREAD

**Issue by fengmk2** [isaacs/minipass#8]
I still finding the root case.

**Comment by jcesarmobile** [comment]
looks like 2.6.3 fixed the issue, at least the one we were having.

**Comment by also** [comment]
2.6.3 fixed it for us. Our issue was that tar 4.4.10 would apparently stop processing a stream, leaving the Node.js event loop empty and allowing the process to exit.

**Comment by techarendra** [comment]
Getting the error "No matching version found for minipass@^2.6.4" when installing bcrypt.
"npm install bcrypt" you will see the above error,

**Comment by fengmk2** [comment]
> 2.6.3 fixed it for us. Our issue was that tar 4.4.10 would apparently stop processing a stream, leaving the Node.js event loop empty and allowing the process to exit.

yep, the same issue for me.

**Comment by fengmk2** [comment]
confirmed has been fixed on minipass@2.6.5
